module.exports = [
  {
    active: false,
    breaking: false,
    added: 1,
    complete: true,
    editing: false,
    elapsed: 4400000,
    id: 1,
    pomodoroGoal: 4,
    title: "A complete task",
  },
  {
    active: false,
    breaking: false,
    added: 3,
    complete: false,
    editing: false,
    elapsed: 6990000,
    id: 2,
    pomodoroGoal: 3,
    title: "Finish Lorem ipsum task. A really long to-do task. No idea why you'd need to make a to do with so much text. This isn't the place to document the story of your life",
  },
  {
    active: false,
    breaking: false,
    added: 2,
    complete: false,
    editing: false,
    elapsed: 1495000,
    id: 3,
    pomodoroGoal: 4,
    title: "5 seconds short of one pomodoro. After one pomodoro (25 minutes) has elapsed, a break timer starts for 5 minutes. This should be skippable",
  },
  {
    active: false,
    breaking: false,
    added: 5,
    complete: false,
    editing: false,
    elapsed: 2998000,
    id: 4,
    pomodoroGoal: 1,
    title: "one second short of two pomodoros",
  },
  {
    active: false,
    breaking: false,
    added: 4,
    complete: false,
    editing: false,
    elapsed: 0,
    id: 5,
    pomodoroGoal: 4,
    title: "Do that one thingsdfsdf sdf sd fsdf sdfsdfsdfsd ffdsfsdfsdfsdf ....llll",
  },
  {
    active: false,
    breaking: false,
    added: 6,
    complete: false,
    editing: false,
    elapsed: 400,
    id: 6,
    pomodoroGoal: 2,
    title: "Fix that other thing",
  },
];
