module.exports = [
  {
    active: false,
    complete: true,
    elapsed: 4400000,
    id: 1,
    pomodoros: 4,
    title: "Finish Cowork Hive member page",
  },
  {
    active: false,
    complete: false,
    elapsed: 2990000,
    id: 2,
    pomodoros: 3,
    title: "Finish Lorem ipsum task. A really long to do task. No idea why you'd need to make a to do with so much text. This isn't the place to document the story of your life",
  },
  {
    active: true,
    complete: false,
    elapsed: 1490000,
    id: 3,
    pomodoros: 4,
    title: "Do laundry",
  },
  {
    active: true,
    complete: false,
    elapsed: 3222222,
    id: 4,
    pomodoros: 1,
    title: "Fix car",
  },
  {
    active: false,
    complete: false,
    elapsed: 0,
    id: 5,
    pomodoros: 4,
    title: "Do that one thing",
  },
  {
    active: true,
    complete: false,
    elapsed: 30000,
    id: 6,
    pomodoros: 2,
    title: "Fix that other thing",
  },
];
